---
#Three node web cluster that are connected to a load balancer
- name: Deploy
  hosts: web
#serialized execution ensures tasks are executed one-by-one (batch size 1)
  serial: 1

  tasks:
    - name: disable node
      debug:
        msg: "disable {{ inventory_hostname }}"
      delegate_to: "{{ groups['lb'][0] }}"

    - name: upgrade web
      debug:
        msg: "upgrade software"

    - name: enable node
      debug:
        msg: "enable {{ inventory_hostname }}"
      delegate_to: "{{ groups['lb'][0] }}"
